config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords" }

  devise_scope :user do 
    match 'users/finish_auth', to:'users/registrations#add_data', as: 'finish_auth', via: [:get, :put]
    get 'users/callback' => 'users/registrations#callback'
    get 'visits/calendars' => 'visits#calendars'
    get 'visits/add', to: 'visits#new', as: 'visits'
    post 'visits/add', to: 'visits#create', as: 'new_visit'
    get 'visits/calendar', to: 'visits#calendar', as: 'show_calendar'
    get 'visits/show_visits', to: 'visits#show', as: 'show_visits'
    post 'delete_visit', to: 'visits#delete_visit', as: 'delete_visit'
    put 'user/:id' => 'users/registrations#update'
    get 'user/:id', to: 'users/registrations#show', as: 'user'
    get 'list_user', to: 'users/registrations#index', as: 'list_user'
    get 'user/:id/edit', to: 'users/registrations#edit', as: 'edit_user'

  end

  root to:         'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  

  get '/account_activations/:id/edit', to: 'account_activations#activate', as: 'account_activation'

end

app/models/visit.rb
class Visit < ActiveRecord::Base

  belongs_to :user

end

app/controllers/visits_controller.rb
require 'google/api_client/client_secrets.rb'
require 'google/apis/calendar_v3'

class VisitsController < ApplicationController

  CALENDAR_ID = "progettoarchitetture@gmail.com"


  def calendar_options
    cal = Google::Apis::CalendarV3::CalendarService.new
    cal.authorization = google_secret.to_authorization
    cal.authorization.refresh!
    cal
  end

  def calendars
    @calendar = calendar_options.list_calendar_lists.items[0]
    render 'appointment'
  end

  def calendar
    render 'visits'
  end

  def show
    @visits_list = current_user.visits
    puts(@visit_list)
  end

  def new
    @visit = Visit.new
    @visit_list = calendar_options.list_events(CALENDAR_ID)
    render 'add_visit'
  end

  def create
    # puts "**************************"
    # puts params[:visits]
    # puts "**************************"
    if params[:visits][:tipo] == "Controllo" || params[:visits][:tipo] == "Visita" || params[:visits][:tipo] == "Operazione"
      visit = Google::Apis::CalendarV3::Event.new({
        start: Google::Apis::CalendarV3::EventDateTime.new(
          date_time: DateTime.parse(params[:visits][:data_inizio] + " " + params[:visits][:ora_inizio]).change(offset:'+0200'),
        ),
        end: Google::Apis::CalendarV3::EventDateTime.new(
          date_time: DateTime.parse(params[:visits][:data_fine] + " " + params[:visits][:ora_fine]).change(offset:'+0200'),
        ),
        summary: current_user.is_doctor? ? params[:visits][:paziente] + " - " + params[:visits][:tipo] + 
                    " - Giorno: " + params[:visits][:data_inizio] + " - Ora: " + params[:visits][:ora_inizio] : 
                    current_user.nome + " " + current_user.cognome + " - " + params[:visits][:tipo] + 
                    " - Giorno: " + params[:visits][:data_inizio] + " - Ora: " + params[:visits][:ora_inizio],
                    
      })

      @visit = Visit.new(visit_params)
      @visit.user = current_user
      if @visit.save
        calendar_options.insert_event(CALENDAR_ID, visit)
        redirect_to show_calendar_url
      else
        flash[:error] = "Errore salvataggio visita nel database"
        redirect_to new_visit_url
      end
    else
      flash[:error] = "Questa non è un'opzione valida"
      redirect_to new_visit_url
    end
  end

  def delete_visit
    visit_id = params[:visits][:visits]
    calendar_options.delete_event(CALENDAR_ID, visit_id)
    flash[:success] = "La visita con id " + visit_id.to_s + " è stata cancellata"
    redirect_to show_calendar_url
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      if current_user.is_doctor
        params.require(:visits).permit(:tipo, :ora_inizio, :ora_fine, :data_inizio, :data_fine, :paziente)
      else
        params.require(:visits).permit(:tipo, :ora_inizio, :ora_fine, :data_inizio, :data_fine)
      end
    end



    def google_secret
      # puts "************************"
      # puts current_user.token
      # puts current_user.refresh_token #For the user Mario Rossi, that is the one that we are interested in
      # puts "************************"
      Google::APIClient::ClientSecrets.new(
        { "web" =>
          {
            "access_token" => "ya29.Glt1B7LwAzpYh4AE0G-8shM1yR1Y4Vmx5GHOlxFISLHi99_cPzfuP7i3dtXcWIppX-yQslMndcdFAUEopkvqdIpSDQf-RCO4mGlPBh_bCc6_tJ2pPG0IZbWwDKwA",
            "refresh_token" => "1/SyLNtRuLtWB8JB7BHTXdr7lTBtt5cf9jP5s2R6FPSTY",
            "client_id" => Rails.application.secrets.google_client_id,
            "client_secret" => Rails.application.secrets.google_client_secret,
          }
        }
      )
    end




  #before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # # GET /visits
  # # GET /visits.json
  # def index
  #   @visits = Visit.all
  # end

  # # GET /visits/1
  # # GET /visits/1.json
  # def show
  # end

  # # GET /visits/new
  # # def new
  # #   @visit = Visit.new
  # # end

  # # GET /visits/1/edit
  # def edit
  # end

  # POST /visits
  # POST /visits.json
  # def create
  #   @visit = Visit.new(visit_params)

  #   respond_to do |format|
  #     if @visit.save
  #       format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
  #       format.json { render :show, status: :created, location: @visit }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @visit.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  # def update
  #   respond_to do |format|
  #     if @visit.update(visit_params)
  #       format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @visit }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @visit.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /visits/1
  # # DELETE /visits/1.json
  # def destroy
  #   @visit.destroy
  #   respond_to do |format|
  #     format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end




end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :inizio %><br>
    <%= f.text_field :inizio %>
  </div>
  <div class="field">
    <%= f.label :fine %><br>
    <%= f.text_field :fine %>
  </div>
  <div class="field">
    <%= f.label :paziente %><br>
    <%= f.number_field :paziente %>
  </div>
  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_area :descrizione %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/add_visit.html.erb
<% provide(:title, 'Prenota Visita') %>

<h1>Prenota Visita</h1>

<!-- <ul>
  <% @visit_list.items.each do |visit| %>
    <li><%= visit.summary %> (<%= visit.id %>)</li>
  <% end %>
</ul> -->

<%= form_for("visits", url: new_visit_url) do |f| %>
    <%= f.label :data_inizio %>
    <%= f.date_field :data_inizio, class: "form-control", placeholder: 'Data inizio' %>
    <br>
    <%= f.label :ora_inizio %>
    <%= f.time_field :ora_inizio, class: "form-control", placeholder: 'Ora inizio' %>
    <br>
    <%= f.label :data_fine %>
    <%= f.date_field :data_fine, class: "form-control", placeholder: 'Data fine' %>
    <br>
    <%= f.label :ora_fine %>
    <%= f.time_field :ora_fine, class: "form-control", placeholder: 'Ora fine' %>
    <br>
    <%= f.label :tipo_visita %>
    <%= f.text_field :tipo, class: "form-control", placeholder: 'Controllo' %>
    <br>
    <% if current_user.is_doctor %>
        <%= f.label :paziente %>
        <%= f.text_field :paziente, class: "form-control", placeholder: 'Paziente' %>
    <% end %>
    <br>

    <%= submit_tag 'Aggiungi Visita', class: "btn btn-primary" %>
<% end %>


<% if current_user.is_doctor %>
    <br><br><br>
    <h1> Cancella visita </h1>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <% if !@visit_list.items.empty? %>
                <%= form_for("visits", url: delete_visit_url, html: { method: :post }) do |f| %>
                    <%= f.select "visits", options_from_collection_for_select(@visit_list.items, "id", "summary") %>
                    <%= submit_tag 'Cancella visita', class: "btn btn-primary" %>
                <% end %>
            <% else %>
                <center><h5> Non ci sono visite da cancellare </h5></center>
            <% end %>
        </div>
    </div>
<% end %>

app/views/visits/appointment.html.erb
<% provide(:title, 'Appointment') %>

<h1>Visite</h1>
<ul>
<b><li><%= @calendar.summary %> (<%= @calendar.id %>)</li></b>
</ul>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visits</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Inizio</th>
      <th>Fine</th>
      <th>Paziente</th>
      <th>Descrizione</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.tipo %></td>
        <td><%= visit.inizio %></td>
        <td><%= visit.fine %></td>
        <td><%= visit.paziente %></td>
        <td><%= visit.descrizione %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<% @visits_list.each do |visit| %>
      <tr>
        <strong>Tipo:</strong>
        <td><%= visit.tipo %></td>
        <strong>Inizio:</strong>
        <td><%= visit.ora_inizio %></td>
        <strong>Fine:</strong>
        <td><%= visit.ora_fine %></td>
        <strong>Paziente:</strong>
        <td><%= visit.paziente %></td>
        <strong>Descrizione:</strong>
        <td><%= visit.descrizione %></td>
  </tr>
  <br>
<% end %>

app/views/visits/visits.html.erb
<% provide(:title, 'Visite') %>

<h1>Visite</h1>

<iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=2&amp;bgcolor=%23ffffff&amp;ctz=Europe%2FRome&amp;src=cHJvZ2V0dG9hcmNoaXRldHR1cmVAZ21haWwuY29t&amp;src=aXQuaXRhbGlhbiNob2xpZGF5QGdyb3VwLnYuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23039BE5&amp;color=%230B8043&amp;title=Dottor%20Mario%20Rossi" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

<br><br><br>

<div class="row">
    <div class="col-md-6 col-md-offset-1">
        <%= button_to "Prenota Visita", visits_url, method: :get, class: 'btn btn-primary' %></p>

        <% if current_user.is_doctor %>
            <%= button_to "Cancella Visita", visits_url, method: :get, class: 'btn btn-primary' %></p>
        <% end %>
    </div>
</div>