config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords" }

  devise_scope :user do 
    match 'users/finish_auth', to:'users/registrations#add_data', as: 'finish_auth', via: [:get, :put]
    get 'users/callback' => 'users/registrations#callback'
    get 'visits/calendars' => 'visits#calendars'
    get 'visits/add', to: 'visits#new', as: 'visits'
    post 'visits/add', to: 'visits#create', as: 'new_visit'
    get 'visits/calendar', to: 'visits#calendar', as: 'show_calendar'
    get 'visits/show_visits', to: 'visits#show', as: 'show_visits'
    post 'delete_visit', to: 'visits#delete_visit', as: 'delete_visit'
    put 'user/:id' => 'users/registrations#update'
    get 'user/:id', to: 'users/registrations#show', as: 'user'
    get 'list_user', to: 'users/registrations#index', as: 'list_user'
    get 'user/:id/edit', to: 'users/registrations#edit', as: 'edit_user'

  end

  root to:         'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  

  get '/account_activations/:id/edit', to: 'account_activations#activate', as: 'account_activation'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Studio Odontoiatrico
  </small>
  <nav>
    <ul>
      <li><%= link_to "Chi Siamo",   about_path %></li>
      <li><%= link_to "Contattaci", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Home", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <!-- <li><%= link_to "Help",   help_path %></li> -->
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profilo", current_user %></li>
              <li><%= link_to "Impostazioni", edit_user_path(current_user) %></li>
              <li><%= link_to "Calendario visite", show_calendar_path %></li>
              <li><%= link_to "Prenota visita", new_visit_path %></li>
              <% if current_user.is_doctor %>
                <li><%= link_to "Pazienti", list_user_path %></li>
              <% end %>

              <li class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
        <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
  </body>
</html>